"""empty message

Revision ID: cf0cc5f8f7ab
Revises: 53e1c1bd9e83
Create Date: 2020-06-02 22:42:13.189765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0cc5f8f7ab'
down_revision = '53e1c1bd9e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute("UPDATE todos SET completed=False WHERE completed IS NULL")

    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
