"""empty message

Revision ID: 832fee365e65
Revises: 56fca416b950
Create Date: 2020-06-08 19:06:37.979015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832fee365e65'
down_revision = '56fca416b950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('image_link', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'image_link')
    # ### end Alembic commands ###
